spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ib
    username: ib
    password: ibib
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret-key: "iegfjrfbvhwh349ur023fcdxsretyyhujoytr6e4waeszxdcfgvhj"
    expiration: 3600000

logging:
  level:
    org.eoeqs: INFO
    org.springframework.security: WARN