spring:
  datasource:
    url: jdbc:postgresql://dev-pg12:5432/ib
    username: ib
    password: ibib
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jwt:
    secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    expiration: 86400000

server:
  port: 8080

logging:
  level:
    org.eoeqs: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG