name: Security CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application (skip tests)
        run: mvn clean compile -DskipTests

      - name: Package application
        run: mvn package -DskipTests

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Java version:"
          java -version
          echo "Maven version:"
          mvn --version

      - name: Build for security analysis
        run: mvn compile -DskipTests

      - name: SAST - Generate SpotBugs HTML report
        run: |
          # Генерируем HTML отчет SpotBugs
          mvn spotbugs:spotbugs -Dspotbugs.htmlOutput=true -Dspotbugs.htmlOutputDirectory=target/spotbugs-html
        continue-on-error: true

      - name: SAST - Run SpotBugs check
        run: |
          mvn spotbugs:check || echo "SpotBugs check completed with findings"
        continue-on-error: true

      - name: SAST - Upload SpotBugs XML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-xml-report
          path: target/spotbugs/

      - name: SAST - Upload SpotBugs HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-html-report
          path: target/spotbugs-html/

      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk --version

      - name: SCA - Run Snyk security scan
        run: |
          export JAVA_HOME=${JAVA_HOME}
          echo "Using JAVA_HOME: $JAVA_HOME"
          snyk test --file=pom.xml --sarif-file-output=snyk-results.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: SCA - Upload Snyk report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-report
          path: snyk-results.sarif

      - name: Security scan summary
        run: |
          echo "=== Security Scan Summary ==="
          echo "SpotBugs: XML and HTML reports generated"
          echo "Snyk: Vulnerability assessment completed"
          echo "All reports available as artifacts"

